import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser()

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Twitter</h1>
        {user.isSignedIn && <SignOutButton />}
        {!user.isSignedIn && <SignInButton />}
      </main>
    </>
  );
};

export default Home;
