import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import { CreatePostWizard } from "~/pages/components/CreatePostWizard";
import { PostView } from "~/pages/components/PostView";

const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) {
    return <div>Loading...</div>
  }

  if (!data) {
    return <div>No data</div>
  }

  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full md:max-w-2xl border-x border-slate-400 h-full">
          <div className="flex border-b border-slate-400 p-4">
            <div className="flex justify-center">
              {user.isSignedIn && <CreatePostWizard />}
              {!user.isSignedIn && <SignInButton />}
            </div>
          </div>

          <div className="flex flex-col">
            {data.map((postWithUser) => (
              <PostView key={postWithUser.post.id} postWithUser={postWithUser}  />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
