import Head from "next/head";

const Post = () => {

  return <>
    <Head>
      <title>Post</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex h-screen justify-center">
      <div className="w-full md:max-w-2xl border-x border-slate-400 h-full">
        post

      </div>
    </main>
  </>
}

export default Post